### ISSUE TITLE
TypeError on  function:Timer status and reset

### ISSUE THREAD

**Issue by jacintomfr** [Psynosaur/DATV-Simple#1]
Hi Ohan, I'm testing new version and when I do Deploy I don't have any error or alert but on the log I have:

8 Oct 08:50:41 - [error] [function:Timer status and reset] TypeError: imagesize.trim is not a function

all the time, hourglass is installed ...

How can I solve this ? 

thank you

Jacinto
CU2ED

**Comment by Psynosaur** [comment]
hey please pull latest commit :)
