### ISSUE TITLE
Improvement of the GUI for Longmynd

### ISSUE THREAD

**Issue by hb9dug** [Psynosaur/DATV-Simple#10]
Bonjour Ohan,

I would like to submit to you an improvement of the DATV-Simple GUI for the embeded Longmynd of the PlutoDVB2 firmware.

Longmynd is very efficient and in particular, it's quick lock time. I think it merits to be highlighed in DATV-Simple as it also completes your goal of integrating everything in one software.

To give you some idea, I have attached my flow for Longmynd.

Looking forawrd reading you.

73 qro de michel, hb9dug
[flows-longmynd.json](https://github.com/Psynosaur/DATV-Simple/files/13403033/flows-longmynd.json)
![longmynd-gui](https://github.com/Psynosaur/DATV-Simple/assets/45885858/815a5370-af12-4b80-aa36-e6c2ce5211d1)

**Comment by Psynosaur** [comment]
Hey

If you can help me get it up and running then I could implement it.

Currently it tunes and locks very quickly, yet I can't get any TS data on `230.0.0.1:10000` or `230.0.0.1:1234`

Ive also tried setting tsip with `cmd/longmynd/tsip` to no avail.

ffplay stays blank

**Comment by hb9dug** [comment]
Bonsoir Ohan,

I didn't send you a working program but just the flow to receive as example...
Here is a complete directory to unzip and hopefully by running your magic DATV-Start.cmd should be OK... 
I am setting global parameters in node-red under Settings - Environnement.
You should be able to see the TS with VLC or SMPlayer

Download here : [](https://www.swisstransfer.com/d/23534700-817d-48f2-afd6-805caa74ffab)

73 qro de michel, hb9dug

**Comment by Psynosaur** [comment]
Good morning 

It seems I had to tell my firewall of my home network to allow the Pluto to send to `230.0.0.2:1234`, when I fired up my modified flow from importing you first json, it just worked :)

![image](https://github.com/Psynosaur/DATV-Simple/assets/26934113/5fef3c2d-0d76-4425-8aa2-81b3e27c1d78)

![image](https://github.com/Psynosaur/DATV-Simple/assets/26934113/f52b9216-17f9-49d1-b834-b92a9c539a67)

I will now definitely be integrating this :) 

Kind regards
