### ISSUE TITLE
Change of labels suggestion

### ISSUE THREAD

**Issue by ax25** [Psynosaur/DATV-Simple#11]
To start a transmission we have so many parameters to set in order to configure the modulator (pluto) and the encoder (ffmpeg).

Talking to some colleagues I saw that there is confusion between the pluto (for instance why or when to change the pluto firmware) and the encoder+modulator control (what actually does a software like DATV Easy or Simple). That is because there are modulator controls on many places (DATV Easy and in the internal Pluto web control), and the encoder and modulator parameters are closely related (you set up symbol rate and FEC -modulator- and you get an available bitrate -encoder-).

I think it is important to set a common language so we can understand when we are setting parameters on the modulator side, and what is actually setting up the encoder side or ffmpeg in our case.

My suggestion is to change "Profile controls" for "Encoder controls" or just "Encoder". The start button would be for instance "Start Encoder".
In the current "TX controls" side, I would suggest to write "Modulator control", to understand that we are setting up the modulator parameters and starting RF at the modulator side. The Start button could say "RF ON".

**Comment by Psynosaur** [comment]
Hi

![image](https://github.com/Psynosaur/DATV-Simple/assets/26934113/4c067a33-27e9-40e1-93ba-c57d909b2d89)

is this what you have in mind?

**Comment by ax25** [comment]
Yes :)
