### ISSUE TITLE
No video bitrate info on custom profile

### ISSUE THREAD

**Issue by jacintomfr** [Psynosaur/DATV-Simple#2]
Hi Ohan, 

On custom profile there is Ts bitrate ant Video bitrate info but on this last one I have akways "NaN"

this is the result on debug: 

08/10/2023, 16:41:39[node: debug Video bitrate](http://127.0.0.1:1880/#)
dt/pluto/CU2ED/tx/dvbs2/sr : msg.vidbr : string[3]
"NaN"

Can you help me ?

thank you

Jacinto
cu2ed

**Comment by Psynosaur** [comment]
Hey

Please pull latest commit.

I will redo the way state is managed as I remove all the bat files.

Regards

**Comment by Psynosaur** [comment]
Should be fixed now :)
