### ISSUE TITLE
[error] [calculator:Hz to kHz] 

### ISSUE THREAD

**Issue by jacintomfr** [Psynosaur/DATV-Simple#6]
Hi, 

this last screen layout is great, but today I update for the last version and I have a couple of problems:

1) I have this error on debug: 20 Oct 09:27:31 - [error] [calculator:Hz to kHz] The msg.undefined should only contain number(s)

2) If I turn terminate node red and start again it won't memorize my call name and pluto ip

3) If I click on spectrum slot frequency, it won't show the ch and the frequency is allways the same and it shows RX

The way I install is always the same and until now everything worked at first time, do I miss something ?

again great job, thank you !!!

73

Jacinto
cu2ed

**Comment by jacintomfr** [comment]
Hi, it seems RX/TX must have data, after that seems to work and I don't have the msg on debug ...
TX frequency change but sometimes channels list appear and sometimes it's blank.
Maybe I still missing any parameters ?

Jacinto
cu2ed

**Comment by Psynosaur** [comment]
Hey

I'm updating the code to accommodate restarts of node-red and restarts of flows(re-deploy).

It seems like I can't get things to misbehave anymore.

The channel names being blank, is each pluto tunes to a unique frequency for each channel.
Mine is 2403249920 for CH1, 2403500030 for CH2 and 2403749886 for CH3.

Tune your pluto by clicking channels on spectrum and set those in the channels node for each of the blank ones, if the cosmetic is of concern.

Regards

**Comment by jacintomfr** [comment]
> Hey
> 
> I'm updating the code to accommodate restarts of node-red and restarts of flows(re-deploy).
> 
> It seems like I can't get things to misbehave anymore.
> 
> The channel names being blank, is each pluto tunes to a unique frequency for each channel. Mine is 2403249920 for CH1, 2403500030 for CH2 and 2403749886 for CH3.
> 
> Tune your pluto by clicking channels on spectrum and set those in the channels node for each of the blank ones, if the cosmetic is of concern.
> 
> Regards

Hi, 

Thank you, now I understand the unique frequency and I correct that on the flow and now I have all channels name :-)

Jacinto

**Comment by Psynosaur** [comment]
Hey please check this new feature.

https://youtu.be/-ZdQOVg26_0

**Comment by jacintomfr** [comment]
Hi Ohan,

Brilliant idea ...

Jacinto
cu2ed
