### ISSUE TITLE
RX : clic on Beacon not possible

### ISSUE THREAD

**Issue by hb9dug** [Psynosaur/DATV-Simple#7]
Beacon is usefull to check that the reception chaine is in working order.

On actual version 1.995, this is not possible.

Thank you for your developpement which is very stimulating !  I am learning a lot on NR programming by looking at you code !

Cordialement,
Michel

**Comment by Psynosaur** [comment]
Hey

It is now

![image](https://github.com/Psynosaur/DATV-Simple/assets/26934113/741a54a1-1d54-4903-8ba9-daf87b03740a)

Regards
