### ISSUE TITLE
What contains your MiniTioune_V1_0_1_1c.bat file

### ISSUE THREAD

**Issue by hb9dug** [Psynosaur/DATV-Simple#8]
73 qro de michel, hb9dug

**Comment by Psynosaur** [comment]
hi

I don't know what file you're referring to ¯\_(ツ)_/¯ 

regards

**Comment by Psynosaur** [comment]
perhaps you mean this

![image](https://github.com/Psynosaur/DATV-Simple/assets/26934113/1b437210-24de-4943-b916-2019dcb8407b)

this is for tuning with the minitioune app using CTRL + CLICK

please change to the path of `your` minitioune app.

regards
